"""
This code sets up a simple interactive chatbot
that uses the OpenAI API to  that uses the OpenAI API
to generate responses  to user input. It continuously promtps the user for input
using an infinite for loop, and exits the program if the user types "exit"
"""

# Import necessary libraries
import os
import openai

# Set OpenAI API key
openai.api_key = os.getenv("OpenAi API key")

# Start an infinite loop to keep prompting for user input
while True:
  
  # Get user input
  question = input("\033[34mWhat is your question?\n\033[0m")
  
  # If user types "exit", break out of the loop and end the program
  if question.lower() == "exit":
    print("\033[31mGoodbye!\033[0m")
    break
  
  # Create a chat completion using the OpenAI API with the user's question
  completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
      {"role": "system", "content": "You are a helpful assistant. Answer the given question."},
      {"role": "user", "content": question}
    ]
  )
  
  # Print the response generated by the OpenAI API
  print("\033[32m" + completion.choices[0].message.content + "\n")
  